branches:
  only:
  - master

install:
 - npm install -g firebase-tools
 - npm install

script:
 - npm run build

deploy:
 skip_cleanup: true
 provider: firebase
 token:
  secure: 1/7bvQxKdZZo-1XddiJKUmC414cynpT0Qiom8FRoaoWtU

language: node_js
node_js: "8.11.1"
