deploy:
 - skip_cleanup: true
install:
 - gem install dpl
 - npm install -g firebase-tools
 - npm install

script:
 - npm run build

after_success:
 - dpl --provider=firebase --token=1/7bvQxKdZZo-1XddiJKUmC414cynpT0Qiom8FRoaoWtU --project=act-real-friendz

language: node_js
node_js: "8.11.1"
